window.WMSkyDungeonNamesEn = {
  "1": "Beach Cave",
  "3": "Drenched Bluff",
  "4": "Mt. Bristle",
  "6": "Waterfall Cave",
  "7": "Apple Woods",
  "8": "Craggy Coast",
  "10": "Mt. Horn",
  "12": "Foggy Forest",
  "14": "Steam Cave",
  "17": "Amp Plains",
  "20": "Northern Desert",
  "21": "Quicksand Cave",
  "24": "Crystal Cave",
  "25": "Crystal Crossing",
  "34": "Hidden Land",
  "35": "Brine Cave",
  "44": "Treeshroud Forest",
  "46": "Blizzard Island",
  "47": "Crevice Cave",
  "50": "Surrounded Sea",
  "51": "Miracle Sea",
  "62": "Mt. Travail",
  "64": "Spatial Rift",
  "67": "Dark Crater",
  "70": "Concealed Ruins",
  "72": "Marine Resort",
  "73": "Bottomless Sea",
  "75": "Shimmer Desert",
  "77": "Mt. Avalanche",
  "79": "Giant Volcano",
  "81": "World Abyss",
  "83": "Sky Stairway",
  "85": "Mystery Jungle",
  "87": "Serenity River",
  "88": "Landslide Cave",
  "89": "Lush Prairie",
  "90": "Tiny Meadow",
  "91": "Labyrinth Cave",
  "92": "Oran Forest",
  "93": "Lake Afar",
  "94": "Happy Outlook",
  "95": "Mt. Mistral",
  "96": "Shimmer Hill",
  "97": "Lost Wilderness",
  "98": "Midnight Forest",
  "99": "Zero Isle North",
  "100": "Zero Isle East",
  "101": "Zero Isle West",
  "102": "Zero Isle South",
  "103": "Zero Isle Center",
  "107": "Oblivion Forest",
  "108": "Treacherous Waters",
  "109": "Southeastern Islands",
  "110": "Inferno Cave"
};
